### ISSUE TITLE
Start or Restart Nginx even in case of not resolvable services

### ISSUE THREAD

**Issue by m4r10k** [n0r1sk/ingress-controller#13]
Start or restart the Nginx process, even if not all services are online. This will change the current logic and in case of a miss configuration, the running Nginx process may die.

**Comment by rauschbit** [comment]
started on border controller now - everything working as expected - will let it run for a while and have an eye on it...

**Comment by rauschbit** [comment]
running since yesterday - looks stable for me, also regarding the memory allocation...
